### ISSUE TITLE
DocFX search doesn't function when lightbox plugin is applied

### ISSUE THREAD

**Issue by cedar-ave** [roel4ez/docfx-lightbox-plugin#2]
Thank you for the lightbox plugin for DocFX. When I apply the lightbox plugin, it works great. However, the search bar then returns no results.  When the lightbox plugin is not applied, the search bar returns results. Any thoughts as to what I'm doing wrong? Thank you for any help.

**Comment by roel4ez** [comment]
Hi @cedar-ave , thanks for reporting this. I will look into when I get some time. 
Which version are you using? The Featherlight or Bootstrap version?
Are you using any other templates?

Thanks

**Comment by cedar-ave** [comment]
I tried it with both the Featherlight and Bootstrap versions with the same result. I'm using it with the default DocFX template like shown in the readme. Thanks for this help - this is a great template.

**Comment by andreasblueher** [comment]
Hey, having the same issue. Any news on when you'll have time to look into this?

**Comment by roel4ez** [comment]
Fixed with PR #3 
Thanks @cedar-ave !
